name: CI

on:
  push:
    branches: [main]
  pull_request:
    barnches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6

      - name: 安装python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: pip install pytest requests allure-pytest


      - name: 启动mock服务并运行测试
        run: |
          python login_mock.py 8000 &
          sleep 2
          curl --fail -s http://127.0.0.1:8000/login || exit 1
          pytest -v --alluredir=allure-results

      - name: 生成allure报告
        if: always()
        run: |
          curl -sLO https://github.com/allure-framework/allure2/releases/download/2.44.0/allure-2.44.0.zip
          unzip -q allure-2.44.0.zip
          allure-2.44.0/bin/allure generate allure-results -o allure-report --clean

      - name: 报告上传
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

