name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v6

      - name: 安装python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: pip install pytest requests


      - name: 启动mock服务 并运行测试
        run: |
          python login_mock.py 8000 &
          sleep 2
          curl --fail -s http://127.0.0.1:8000/login || exit 1
          pytest -v



